### ISSUE TITLE
Linux(Arch): OSError: [Errno 2] No such file or directory when attempting to build rpm and deb images with build_all

### ISSUE THREAD

**Issue by topik0** [Windscribe/desktop-v2#4]
```
INFO: Creating Debian package...
dpkg-deb: building package 'windscribe' in '/home/daniel/Documents/RandomClones/desktop-v2/temp/installer/InstallerFiles/../windscribe_2.3.11_beta_amd64.deb'.
Traceback (most recent call last):
  File "./build_all.py", line 747, in <module>
    BuildAll()
  File "./build_all.py", line 685, in BuildAll
    BuildInstallerLinux(configdata, qt_root)
  File "./build_all.py", line 619, in BuildInstallerLinux
    iutl.RunCommand(["fpm", "-s", "deb", "-p", rpm_package_name, "-t", "rpm", dest_package_path + ".deb"])
  File "/home/daniel/Documents/RandomClones/desktop-v2/tools/deps/installutils.py", line 180, in RunCommand
    proc.ExecuteWithRealtimeOutput(command_and_args, env=env, shell=shell)
  File "/home/daniel/Documents/RandomClones/desktop-v2/tools/base/process.py", line 27, in ExecuteWithRealtimeOutput
    process_handle = subprocess.Popen(command_and_args, stdout=subprocess.PIPE, env=env, shell=shell)
  File "/home/daniel/.pyenv/versions/2.7.18/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/home/daniel/.pyenv/versions/2.7.18/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
I am getting the output above when running ``./build_all --no-sign``.  I am on Arch and I have dpkg and fpm installed.  Not sure what the issue is here, everything seems fine.

**Comment by bernerdad** [comment]
Hi.  The build process is not currently tested on Arch.  We've updated the readme to indicate the distros and compilers we have tested the build process on.  It is on our roadmap to add support in a future release.  Cheers!
